<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('create an private album with 5 media and see private album with 5 media');
$I->login();
$I->amOnPage("/members/demo/media/album/");
$I->click(['id'=>'rtm-media-options-list']);
$I->click(['class'=>'rtm-options']);
$I->wait(2);
$I->fillField(['id'=>'rtmedia_album_name'],'TexasBlue');
$I->clickWithLeftButton(['id'=> 'rtmedia_create_new_album']);
$I->wait(2);
$I->see('TexasBlue album created successfully.');
$I->clickWithLeftButton(['class'=> 'mfp-close']);
$I->wait(2);
$I->reloadPage();
$I->click('TexasBlue');
$I->wait(2);
$I->click(['id'=>'rtm_show_upload_ui']);
$I->selectOption(['id'=>'rtSelectPrivacy'], array('value' => '60'));
$I->attachFile( 'input[type="file"]', 'blue bonnets.jpg' );
$I->attachFile( 'input[type="file"]', 'texasblue1.jpg' );
$I->attachFile( 'input[type="file"]', 'texasblue3.jpg' );
$I->attachFile( 'input[type="file"]', 'texasblue3.jpg' );
$I->attachFile( 'input[type="file"]', 'texasblue4.jpg' );
$I->wait(2);
$I->click('Start upload');
$I->wait(10);
$I->click(['id'=>'rtmedia-nav-item-albums']);
$I->wait(1);
$I->see('TexasBlue');
$I->see('5');
$I->click('TexasBlue');
$I->click(['id'=>'rtm-media-options-list']);
$I->click('Delete Album');
$I->acceptPopup();
$I->wait(3);
$I->click('Log Out');